## Inevitable Policy Response

The TDM indicates the degree of disruption that your portfolio could experience in 6 to 9 years. This metric measures the adjustments (e.g. decline of coal mining, oil production, increase in renewable power, etc.) needed in the portfolio from year 6 to 9 (2026 - 2030) relative to the portfolio's pace in years 1 to 5 (2021-2025), in order to be aligned with required decarbonization levels by the FPS (Forecast Policy Scenario) scenario by the end of 2030. A high number means that companies in your portfolio will need to significantly adjust their decarbonization pace in years 6-9 to meet the 2030 goals of the FPS. Thus, the higher the number, the higher the likely portfolio disruption in the medium-term. This metric is meant to be complementary to the alignment model, in the sense that the investors who want to mitigate the policy risk would need to move ahead of the FPS scenario. If investors want a smooth transition to the scenario, they should start adjusting or engaging with companies at a faster or slower pace according to their results.

<div id="speedometer_dashboard_equity" class="has_optbar donotduplicate donotremove"></div>
<div id="speedometer_dashboard_bonds" class="has_optbar donotduplicate donotremove"></div>

<details>
<summary> Understanding the Graph </summary>
<div class="method">
<p>This graph shows the Transition Disruption Metric (TDM) at a portfolio level and at 
technology levels within a sector. The portfolio-level result is displayed in the upper 
gauge and the technology-level results are displayed below it. The default sector for 
technology results is ‘Automotive’ and the user can change the selection by clicking on 
the sector name in the title of this part of the chart and choosing a different sector. Only 
the sectors to which the user’s portfolio is exposed are displayed in the chart. The brown
pointer indicates the TDM result calculated for user’s portfolio (at either portfolio o 
technology level), and the black line indicates the TDM result for the FPS (Forecast 
Policy Scenario) scenario. Thus, similar to the user's TDM, the higher the TDM for the FPS, the higher the level of disruption in the scenario itself.

The transition risk based on the TDM metric is considered to be:
<ul>
<li>‘Fully Mitigated’ if TDM is equal to 0,</li>
<li>‘Manageably Mitigated’ if TDM is between 0 and 1,</li>
<li> ‘Manageably disruptive’ if TDM falls between 1 and 1.5,</li>
<li> ‘Unmanagbly disruptive’ if TDM is above 1.5.</li>
</ul>

Here is how the TDM can be understood using the example of writing a one page letter in one hour, where 
we track progress / disruption:
<ul>
<li>If you wrote the letter in 30 minutes, your TDM is 0. Your work is done ahead of 
time.</li>
<li>If you wrote half the letter in 30 minutes, your TDM is 1. You are on track to finish
the letter within the hour.</li>
<li>If you wrote only a quarter of a page in 30 minutes, your disruption is 1.5. You 
are significantly behind finish the letter and need to accelerate, but it is probably 
manageable still.</li>
<li>Anything above 1.5 (anything less than the quarter of the work done after half the
time spent) involves significant disruption.</li>
</ul>

Hovering over some elements of the chart will display their corresponding values.
</p>
</div>
</details>
