#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom countrycode countrycode
#' @importFrom dplyr %>%
#' @importFrom dplyr across
#' @importFrom dplyr any_of
#' @importFrom dplyr arrange
#' @importFrom dplyr bind_rows
#' @importFrom dplyr c_across
#' @importFrom dplyr case_when
#' @importFrom dplyr cur_group_id
#' @importFrom dplyr desc
#' @importFrom dplyr distinct
#' @importFrom dplyr everything
#' @importFrom dplyr filter
#' @importFrom dplyr group_by
#' @importFrom dplyr if_else
#' @importFrom dplyr lag
#' @importFrom dplyr left_join
#' @importFrom dplyr min_rank
#' @importFrom dplyr mutate
#' @importFrom dplyr mutate_at
#' @importFrom dplyr n
#' @importFrom dplyr pull
#' @importFrom dplyr rename
#' @importFrom dplyr row_number
#' @importFrom dplyr rowwise
#' @importFrom dplyr select
#' @importFrom dplyr slice
#' @importFrom dplyr summarise
#' @importFrom dplyr tibble
#' @importFrom dplyr transmute
#' @importFrom dplyr ungroup
#' @importFrom fs path
#' @importFrom jsonlite read_json
#' @importFrom jsonlite toJSON
#' @importFrom readr cols_only
#' @importFrom readr read_csv
#' @importFrom readr write_csv
#' @importFrom rlang :=
#' @importFrom rlang .data
#' @importFrom rlang .env
#' @importFrom stats setNames
#' @importFrom stringr str_replace
#' @importFrom tidyr pivot_longer
#' @importFrom tidyr pivot_wider
#' @importFrom tidyr unite
#' @importFrom utils packageVersion
#' @importFrom writexl write_xlsx
## usethis namespace: end
NULL
